# Generated by Django 3.0.5 on 2021-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('nome', models.TextField()),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('codigoMedico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.TextField()),
                ('logradouro', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
