# Generated by Django 3.0.5 on 2021-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='id',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
