# Generated by Django 3.0.5 on 2021-08-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('cep', models.TextField()),
                ('logradouro', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciamento.Pessoa')),
                ('dataContrato', models.DateField()),
                ('salario', models.FloatField()),
                ('senhaHash', models.TextField()),
            ],
            bases=('gerenciamento.pessoa',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciamento.Pessoa')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('tipoSanguineo', models.TextField()),
            ],
            bases=('gerenciamento.pessoa',),
        ),
    ]
