# Generated by Django 3.0.5 on 2021-08-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciamento.Funcionario')),
                ('especialidade', models.TextField()),
                ('crm', models.TextField()),
            ],
            bases=('gerenciamento.funcionario',),
        ),
    ]
